# [dbo].[MALIYET]

In [0]:
USE [Northwind]
GO

In [0]:
/****** Object:  UserDefinedFunction [dbo].[MALIYET]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[MALIYET](@BIRIMFIYATI INT, @STOKMIKTARI INT) RETURNS NVARCHAR(MAX)
AS 
	BEGIN
		DECLARE @SONUC INT = @BIRIMFIYATI * @STOKMIKTARI * 1.18
		RETURN @SONUC
	END
GO

# [dbo].[ORNEKFONKSIYON]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[ORNEKFONKSIYON]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[ORNEKFONKSIYON]() RETURNS INT
AS 
	BEGIN
		RETURN 3
	END
GO

# [dbo].[RAPOR]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[RAPOR]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[RAPOR](@KATEGORI NVARCHAR(MAX),@URUNADI NVARCHAR(MAX), @BIRIMFIYATI INT, @STOK INT) RETURNS NVARCHAR(MAX)
AS
	BEGIN
		DECLARE @CIKTI NVARCHAR(MAX) = @KATEGORI + ' kategorisindeki ' + @URUNADI + ' ürününün toplam fiyatı : ' + CAST(@BIRIMFIYATI * @STOK AS NVARCHAR(MAX)) + ' ''DIR.'
		RETURN @CIKTI
	END
GO

# [dbo].[TOPLA]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[TOPLA]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[TOPLA](@SAYI1 INT, @SAYI2 INT) RETURNS INT
AS
	BEGIN
		RETURN @SAYI1 +  @SAYI2
	END
GO

# [dbo].[Kategoriler]

In [0]:
/****** Object:  Table [dbo].[Kategoriler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kategoriler](
	[KategoriID] [int] IDENTITY(1,1) NOT NULL,
	[KategoriAdi] [nvarchar](15) NOT NULL,
	[Tanimi] [ntext] NULL,
	[Resim] [image] NULL,
 CONSTRAINT [PK_Kategoriler] PRIMARY KEY CLUSTERED 
(
	[KategoriID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Satislar]

In [0]:
/****** Object:  Table [dbo].[Satislar]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Satislar](
	[SatisID] [int] IDENTITY(1,1) NOT NULL,
	[MusteriID] [nchar](5) NULL,
	[PersonelID] [int] NULL,
	[SatisTarihi] [datetime] NULL,
	[OdemeTarihi] [datetime] NULL,
	[SevkTarihi] [datetime] NULL,
	[ShipVia] [int] NULL,
	[NakliyeUcreti] [money] NULL,
	[SevkAdi] [nvarchar](40) NULL,
	[SevkAdresi] [nvarchar](60) NULL,
	[SevkSehri] [nvarchar](15) NULL,
	[SevkBolgesi] [nvarchar](15) NULL,
	[SevkPostaKodu] [nvarchar](10) NULL,
	[SevkUlkesi] [nvarchar](15) NULL,
 CONSTRAINT [PK_Satislar] PRIMARY KEY CLUSTERED 
(
	[SatisID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Urunler]

In [0]:
/****** Object:  Table [dbo].[Urunler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Urunler](
	[UrunID] [int] IDENTITY(1,1) NOT NULL,
	[UrunAdi] [nvarchar](40) NOT NULL,
	[TedarikciID] [int] NULL,
	[KategoriID] [int] NULL,
	[BirimdekiMiktar] [nvarchar](20) NULL,
	[BirimFiyati] [money] NULL,
	[HedefStokDuzeyi] [smallint] NULL,
	[YeniSatis] [smallint] NULL,
	[EnAzYenidenSatisMikatari] [smallint] NULL,
	[Sonlandi] [bit] NOT NULL,
 CONSTRAINT [PK_Urunler] PRIMARY KEY CLUSTERED 
(
	[UrunID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Satis Detaylari]

In [0]:
/****** Object:  Table [dbo].[Satis Detaylari]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Satis Detaylari](
	[SatisID] [int] NOT NULL,
	[UrunID] [int] NOT NULL,
	[BirimFiyati] [money] NOT NULL,
	[Miktar] [smallint] NOT NULL,
	[İndirim] [real] NOT NULL,
 CONSTRAINT [PK_Order_Details] PRIMARY KEY CLUSTERED 
(
	[SatisID] ASC,
	[UrunID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Personeller]

In [0]:
/****** Object:  Table [dbo].[Personeller]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personeller](
	[PersonelID] [int] IDENTITY(1,1) NOT NULL,
	[SoyAdi] [nvarchar](20) NOT NULL,
	[Adi] [nvarchar](10) NOT NULL,
	[Unvan] [nvarchar](30) NULL,
	[UnvanEki] [nvarchar](25) NULL,
	[DogumTarihi] [datetime] NULL,
	[IseBaslamaTarihi] [datetime] NULL,
	[Adres] [nvarchar](60) NULL,
	[Sehir] [nvarchar](15) NULL,
	[Bolge] [nvarchar](15) NULL,
	[PostaKodu] [nvarchar](10) NULL,
	[Ulke] [nvarchar](15) NULL,
	[EvTelefonu] [nvarchar](24) NULL,
	[Extension] [nvarchar](4) NULL,
	[Fotograf] [image] NULL,
	[Notlar] [ntext] NULL,
	[BagliCalistigiKisi] [int] NULL,
	[FotografPath] [nvarchar](255) NULL,
 CONSTRAINT [PK_Personeller] PRIMARY KEY CLUSTERED 
(
	[PersonelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[VW_GOTUR]

In [0]:
/****** Object:  View [dbo].[VW_GOTUR]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW  [dbo].[VW_GOTUR]
AS 
SELECT P.Adi + ' ' + P.SoyAdi [ADI SOYADI], K.KategoriAdi [KATEGORİ ADI], COUNT(S.SatisID) [TOPLAM SATIŞ] FROM Personeller P 
INNER JOIN Satislar S ON P.PersonelID = S.PersonelID 
INNER JOIN [Satis Detaylari] SD ON S.SatisID = SD.SatisID 
INNER JOIN Urunler U ON U.UrunID = SD.UrunID 
INNER JOIN Kategoriler K ON K.KategoriID = U.KategoriID 
GROUP BY P.Adi + ' ' + P.SoyAdi , K.KategoriAdi
GO

# [dbo].[ORNEKVIEWPERSONELLER]

In [0]:
/****** Object:  View [dbo].[ORNEKVIEWPERSONELLER]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ORNEKVIEWPERSONELLER]
AS 
SELECT Adi,SoyAdi,Unvan FROM Personeller
GO

# [dbo].[Musteriler]

In [0]:
/****** Object:  Table [dbo].[Musteriler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Musteriler](
	[MusteriID] [nchar](5) NOT NULL,
	[SirketAdi] [nvarchar](40) NOT NULL,
	[MusteriAdi] [nvarchar](30) NULL,
	[MusteriUnvani] [nvarchar](30) NULL,
	[Adres] [nvarchar](60) NULL,
	[Sehir] [nvarchar](15) NULL,
	[Bolge] [nvarchar](15) NULL,
	[PostaKodu] [nvarchar](10) NULL,
	[Ulke] [nvarchar](15) NULL,
	[Telefon] [nvarchar](24) NULL,
	[Faks] [nvarchar](24) NULL,
 CONSTRAINT [PK_Musteriler] PRIMARY KEY CLUSTERED 
(
	[MusteriID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Tedarikciler]

In [0]:
/****** Object:  Table [dbo].[Tedarikciler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tedarikciler](
	[TedarikciID] [int] IDENTITY(1,1) NOT NULL,
	[SirketAdi] [nvarchar](40) NOT NULL,
	[MusteriAdi] [nvarchar](30) NULL,
	[MusteriUnvani] [nvarchar](30) NULL,
	[Adres] [nvarchar](60) NULL,
	[Sehir] [nvarchar](15) NULL,
	[Bolge] [nvarchar](15) NULL,
	[PostaKodu] [nvarchar](10) NULL,
	[Ulke] [nvarchar](15) NULL,
	[Telefon] [nvarchar](24) NULL,
	[Faks] [nvarchar](24) NULL,
	[WebSayfasi] [ntext] NULL,
 CONSTRAINT [PK_Tedarikciler] PRIMARY KEY CLUSTERED 
(
	[TedarikciID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Sehirlere Gore Musteri ve Tedarikciler]

In [0]:
/****** Object:  View [dbo].[Sehirlere Gore Musteri ve Tedarikciler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Sehirlere Gore Musteri ve Tedarikciler] AS
SELECT Sehir, SirketAdi, MusteriAdi, 'Musteriler' AS Relationship 
FROM Musteriler
UNION SELECT Sehir, SirketAdi, MusteriAdi, 'Tedarikciler'
FROM Tedarikciler
--ORDER BY Sehir, SirketAdi
GO

# [dbo].[Alfabetik Sirali Urunler Listesi]

In [0]:
/****** Object:  View [dbo].[Alfabetik Sirali Urunler Listesi]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Alfabetik Sirali Urunler Listesi] AS
SELECT Urunler.*, Kategoriler.KategoriAdi
FROM Kategoriler INNER JOIN Urunler ON Kategoriler.KategoriID = Urunler.KategoriID
WHERE (((Urunler.Sonlandi)=0))
GO

# [dbo].[Biten Urunler Listesi]

In [0]:
/****** Object:  View [dbo].[Biten Urunler Listesi]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Biten Urunler Listesi] AS
SELECT Urun_List.UrunID, Urun_List.UrunAdi
FROM Urunler AS Urun_List
WHERE (((Urun_List.Sonlandi)=0))
--ORDER BY Urun_List.UrunAdi
GO

# [dbo].[Satislar Sorgusu]

In [0]:
/****** Object:  View [dbo].[Satislar Sorgusu]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Satislar Sorgusu] AS
SELECT Satislar.SatisID, Satislar.MusteriID, Satislar.PersonelID, Satislar.SatisTarihi, Satislar.OdemeTarihi, 
	Satislar.SevkTarihi, Satislar.ShipVia, Satislar.NakliyeUcreti, Satislar.SevkAdi, Satislar.SevkAdresi, Satislar.SevkSehri, 
	Satislar.SevkBolgesi, Satislar.SevkPostaKodu, Satislar.SevkUlkesi, 
	Musteriler.SirketAdi, Musteriler.Adres, Musteriler.Sehir, Musteriler.Bolge, Musteriler.PostaKodu, Musteriler.Ulke
FROM Musteriler INNER JOIN Satislar ON Musteriler.MusteriID = Satislar.MusteriID
GO

# [dbo].[Ortalama Maliyetin Uzerindeki Urunler]

In [0]:
/****** Object:  View [dbo].[Ortalama Maliyetin Uzerindeki Urunler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Ortalama Maliyetin Uzerindeki Urunler] AS
SELECT Urunler.UrunAdi, Urunler.BirimFiyati
FROM Urunler
WHERE Urunler.BirimFiyati>(SELECT AVG(BirimFiyati) From Urunler)
--ORDER BY Urunler.BirimFiyati DESC
GO

# [dbo].[Kategorilere Gore Urunler]

In [0]:
/****** Object:  View [dbo].[Kategorilere Gore Urunler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Kategorilere Gore Urunler] AS
SELECT Kategoriler.KategoriAdi, Urunler.UrunAdi, Urunler.BirimdekiMiktar, Urunler.HedefStokDuzeyi, Urunler.Sonlandi
FROM Kategoriler INNER JOIN Urunler ON Kategoriler.KategoriID = Urunler.KategoriID
WHERE Urunler.Sonlandi <> 1
--ORDER BY Kategoriler.KategoriAdi, Urunler.UrunAdi
GO

# [dbo].[FC_GONDER]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[FC_GONDER]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FC_GONDER](@AD NVARCHAR(20), @SOYAD NVARCHAR(20)) RETURNS TABLE 
AS 
	RETURN SELECT Adi, SoyAdi FROM Personeller WHERE Adi = @AD AND SoyAdi = @SOYAD
GO

# [dbo].[Her Uc Aylik Satislar]

In [0]:
/****** Object:  View [dbo].[Her Uc Aylik Satislar]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Her Uc Aylik Satislar] AS
SELECT DISTINCT Musteriler.MusteriID, Musteriler.SirketAdi, Musteriler.Sehir, Musteriler.Ulke
FROM Musteriler RIGHT JOIN Satislar ON Musteriler.MusteriID = Satislar.MusteriID
WHERE Satislar.SatisTarihi BETWEEN '19970101' And '19971231'
GO

# [dbo].[Nakliyeciler]

In [0]:
/****** Object:  Table [dbo].[Nakliyeciler]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Nakliyeciler](
	[NakliyeciID] [int] IDENTITY(1,1) NOT NULL,
	[SirketAdi] [nvarchar](40) NOT NULL,
	[Telefon] [nvarchar](24) NULL,
 CONSTRAINT [PK_Nakliyeciler] PRIMARY KEY CLUSTERED 
(
	[NakliyeciID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Faturalar]

In [0]:
/****** Object:  View [dbo].[Faturalar]    Script Date: 25.06.2023 16:28:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[Faturalar] AS
SELECT Satislar.SevkAdi, Satislar.SevkAdresi, Satislar.SevkSehri, Satislar.SevkBolgesi, Satislar.SevkPostaKodu, 
	Satislar.SevkUlkesi, Satislar.MusteriID, Musteriler.SirketAdi AS MusteriName, Musteriler.Adres, Musteriler.Sehir, 
	Musteriler.Bolge, Musteriler.PostaKodu, Musteriler.Ulke, 
	(Adi + ' ' + SoyAdi) AS PersonelSatislari, 
	Satislar.SatisID, Satislar.SatisTarihi, Satislar.OdemeTarihi, Satislar.SevkTarihi, Nakliyeciler.SirketAdi As NakliyeciName, 
	"Satis Detaylari".UrunID, Urunler.UrunAdi, "Satis Detaylari".BirimFiyati, "Satis Detaylari".Miktar, 
	"Satis Detaylari".İndirim, 
	(CONVERT(money,("Satis Detaylari".BirimFiyati*Miktar*(1-İndirim)/100))*100) AS ExtendedPrice, Satislar.NakliyeUcreti
FROM 	Nakliyeciler INNER JOIN 
		(Urunler INNER JOIN 
			(
				(Personeller INNER JOIN 
					(Musteriler INNER JOIN Satislar ON Musteriler.MusteriID = Satislar.MusteriID) 
				ON Personeller.PersonelID = Satislar.PersonelID) 
			INNER JOIN "Satis Detaylari" ON Satislar.SatisID = "Satis Detaylari".SatisID) 
		ON Urunler.UrunID = "Satis Detaylari".UrunID) 
	ON Nakliyeciler.NakliyeciID = Satislar.ShipVia
GO